import {
  Category,
  Product,
  Banner,
  Coupon,
  Review,
  SiteSettings,
} from './types';

import heroImage from '../assets/images/hero_vortex_fashion_1790956344973.jpg';
import categoryShirtsImage from '../assets/images/category_shirts_vortex_1790956364111.jpg';
import categoryPantsImage from '../assets/images/category_pants_vortex_1790956382275.jpg';
import blackShirtImage from '../assets/images/product_black_shirt_vortex_1790956397815.jpg';
import cargoPantsImage from '../assets/images/product_cargo_pants_vortex_1790956411636.jpg';

export const INITIAL_SETTINGS: SiteSettings = {
  store_name: 'The Vortex Wear',
  business_email: 'support@vortexwear.pk',
  whatsapp_number: '+92 300 1046010',
  currency: 'PKR',
  currency_symbol: '₨',
  free_shipping_threshold: 4000,
  standard_shipping_fee: 250,
  announcement:
    'Complimentary shipping across Pakistan on all orders over ₨ 4,000 · Cash on Delivery Available',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'c-shirts',
    name: 'Shirts',
    slug: 'shirts',
    description:
      'Structured overshirts, refined oxford twill, and modern breathable essentials tailored for everyday elegance.',
    image_url: categoryShirtsImage,
    is_active: true,
    sort_order: 1,
  },
  {
    id: 'c-pants',
    name: 'Pants',
    slug: 'pants',
    description:
      'Precision tailored trousers, tactical utility cargos, and relaxed pleated pants engineered with premium durable fabric.',
    image_url: categoryPantsImage,
    is_active: true,
    sort_order: 2,
  },
];

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'b-hero-1',
    title: 'Define Your Style.',
    description:
      'Modern clothing designed for your everyday style. High-density fabrics, structured tailoring, and contemporary silhouettes.',
    image_url: heroImage,
    button_text: 'Shop Collection',
    button_url: '/shop',
    is_active: true,
    sort_order: 1,
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-1',
    code: 'WELCOME10',
    discount_type: 'percentage',
    discount_value: 10,
    minimum_order_amount: 2000,
    maximum_discount: 1000,
    usage_limit: 500,
    used_count: 24,
    is_active: true,
  },
  {
    id: 'coup-2',
    code: 'VORTEX15',
    discount_type: 'percentage',
    discount_value: 15,
    minimum_order_amount: 5000,
    maximum_discount: 2500,
    usage_limit: 200,
    used_count: 58,
    is_active: true,
  },
  {
    id: 'coup-3',
    code: 'FLAT500',
    discount_type: 'fixed',
    discount_value: 500,
    minimum_order_amount: 3500,
    usage_limit: 100,
    used_count: 12,
    is_active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // =========================
  // SHIRTS
  // =========================

  {
    id: 'prod-s1',
    category_id: 'c-shirts',
    category_slug: 'shirts',
    category_name: 'Shirts',
    name: 'Vortex Onyx Structured Overshirt',
    slug: 'vortex-onyx-structured-overshirt',
    description:
      'Crafted from heavy 320 GSM Japanese cotton twill with custom matte black snap hardware. Designed with twin chest welt pockets, drop shoulders, and a clean structured boxy drape. Ideal as a light jacket over a basic tee or worn buttoned as a modern minimal overshirt.',
    base_price: 5490,
    sale_price: 4690,
    sku: 'VOR-SHT-001',
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: true,
    rating: 4.9,
    review_count: 28,
    images: [
      {
        id: 'img-s1-1',
        product_id: 'prod-s1',
        image_url: blackShirtImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Vortex Onyx Structured Overshirt front view',
      },
      {
        id: 'img-s1-2',
        product_id: 'prod-s1',
        image_url: categoryShirtsImage,
        is_primary: false,
        sort_order: 2,
        alt_text: 'Vortex Onyx Overshirt texture detail',
      },
    ],
    variants: [
      {
        id: 'v-s1-blk-s',
        product_id: 'prod-s1',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'S',
        sku: 'VOR-SHT-001-BLK-S',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 12,
        is_active: true,
      },
      {
        id: 'v-s1-blk-m',
        product_id: 'prod-s1',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'M',
        sku: 'VOR-SHT-001-BLK-M',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 18,
        is_active: true,
      },
      {
        id: 'v-s1-blk-l',
        product_id: 'prod-s1',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'L',
        sku: 'VOR-SHT-001-BLK-L',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 15,
        is_active: true,
      },
      {
        id: 'v-s1-blk-xl',
        product_id: 'prod-s1',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'XL',
        sku: 'VOR-SHT-001-BLK-XL',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 7,
        is_active: true,
      },
      {
        id: 'v-s1-sl-m',
        product_id: 'prod-s1',
        color: 'Slate Grey',
        color_code: '#475569',
        size: 'M',
        sku: 'VOR-SHT-001-SLT-M',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 10,
        is_active: true,
      },
      {
        id: 'v-s1-sl-l',
        product_id: 'prod-s1',
        color: 'Slate Grey',
        color_code: '#475569',
        size: 'L',
        sku: 'VOR-SHT-001-SLT-L',
        price: 5490,
        sale_price: 4690,
        stock_quantity: 9,
        is_active: true,
      },
    ],
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },

  {
    id: 'prod-s2',
    category_id: 'c-shirts',
    category_slug: 'shirts',
    category_name: 'Shirts',
    name: 'Atelier Oxford Tailored Shirt',
    slug: 'atelier-oxford-tailored-shirt',
    description:
      '100% fine Egyptian combed long-staple cotton tailored with a structured button-down collar, natural mother-of-pearl buttons, and rounded barrel cuffs. A timeless staple providing crisp breathability from corporate mornings to evening social settings.',
    base_price: 4290,
    sku: 'VOR-SHT-002',
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: false,
    rating: 4.8,
    review_count: 19,
    images: [
      {
        id: 'img-s2-1',
        product_id: 'prod-s2',
        image_url: categoryShirtsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Atelier Oxford Tailored Shirt in Crisp White',
      },
    ],
    variants: [
      {
        id: 'v-s2-wht-s',
        product_id: 'prod-s2',
        color: 'Crisp White',
        color_code: '#FFFFFF',
        size: 'S',
        sku: 'VOR-SHT-002-WHT-S',
        price: 4290,
        stock_quantity: 14,
        is_active: true,
      },
      {
        id: 'v-s2-wht-m',
        product_id: 'prod-s2',
        color: 'Crisp White',
        color_code: '#FFFFFF',
        size: 'M',
        sku: 'VOR-SHT-002-WHT-M',
        price: 4290,
        stock_quantity: 22,
        is_active: true,
      },
      {
        id: 'v-s2-wht-l',
        product_id: 'prod-s2',
        color: 'Crisp White',
        color_code: '#FFFFFF',
        size: 'L',
        sku: 'VOR-SHT-002-WHT-L',
        price: 4290,
        stock_quantity: 16,
        is_active: true,
      },
      {
        id: 'v-s2-wht-xl',
        product_id: 'prod-s2',
        color: 'Crisp White',
        color_code: '#FFFFFF',
        size: 'XL',
        sku: 'VOR-SHT-002-WHT-XL',
        price: 4290,
        stock_quantity: 8,
        is_active: true,
      },
      {
        id: 'v-s2-blu-m',
        product_id: 'prod-s2',
        color: 'Sky Blue',
        color_code: '#BAE6FD',
        size: 'M',
        sku: 'VOR-SHT-002-BLU-M',
        price: 4290,
        stock_quantity: 11,
        is_active: true,
      },
    ],
    created_at: '2026-03-02T10:00:00Z',
    updated_at: '2026-03-02T10:00:00Z',
  },

  {
    id: 'prod-s3',
    category_id: 'c-shirts',
    category_slug: 'shirts',
    category_name: 'Shirts',
    name: 'Raw Linen Relaxed Camp Collar Shirt',
    slug: 'raw-linen-camp-collar-shirt',
    description:
      'Spun from pure breathable French linen with an airy open camp collar, horizontal hem, and subtle side slits. Garment-washed for instant softness and effortless summer luxury.',
    base_price: 4490,
    sale_price: 3990,
    sku: 'VOR-SHT-003',
    is_active: true,
    is_featured: false,
    is_new_arrival: true,
    is_on_sale: true,
    rating: 4.7,
    review_count: 14,
    images: [
      {
        id: 'img-s3-1',
        product_id: 'prod-s3',
        image_url: categoryShirtsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Raw Linen Relaxed Camp Collar Shirt',
      },
    ],
    variants: [
      {
        id: 'v-s3-san-s',
        product_id: 'prod-s3',
        color: 'Sand Dune',
        color_code: '#D4C5B9',
        size: 'S',
        sku: 'VOR-SHT-003-SAN-S',
        price: 4490,
        sale_price: 3990,
        stock_quantity: 9,
        is_active: true,
      },
      {
        id: 'v-s3-san-m',
        product_id: 'prod-s3',
        color: 'Sand Dune',
        color_code: '#D4C5B9',
        size: 'M',
        sku: 'VOR-SHT-003-SAN-M',
        price: 4490,
        sale_price: 3990,
        stock_quantity: 15,
        is_active: true,
      },
      {
        id: 'v-s3-san-l',
        product_id: 'prod-s3',
        color: 'Sand Dune',
        color_code: '#D4C5B9',
        size: 'L',
        sku: 'VOR-SHT-003-SAN-L',
        price: 4490,
        sale_price: 3990,
        stock_quantity: 12,
        is_active: true,
      },
      {
        id: 'v-s3-blk-m',
        product_id: 'prod-s3',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'M',
        sku: 'VOR-SHT-003-BLK-M',
        price: 4490,
        sale_price: 3990,
        stock_quantity: 10,
        is_active: true,
      },
    ],
    created_at: '2026-03-03T10:00:00Z',
    updated_at: '2026-03-03T10:00:00Z',
  },

  {
    id: 'prod-s4',
    category_id: 'c-shirts',
    category_slug: 'shirts',
    category_name: 'Shirts',
    name: 'Monochrome Minimalist Poplin Shirt',
    slug: 'monochrome-minimalist-poplin-shirt',
    description:
      'High-thread-count washed poplin with a concealed clean front placket and knife-edge collar. Seamless design free of excess stitching for a razor-sharp modern profile.',
    base_price: 3890,
    sku: 'VOR-SHT-004',
    is_active: true,
    is_featured: false,
    is_new_arrival: false,
    is_on_sale: false,
    rating: 4.6,
    review_count: 8,
    images: [
      {
        id: 'img-s4-1',
        product_id: 'prod-s4',
        image_url: blackShirtImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Monochrome Minimalist Poplin Shirt',
      },
    ],
    variants: [
      {
        id: 'v-s4-blk-m',
        product_id: 'prod-s4',
        color: 'Matte Charcoal',
        color_code: '#27272A',
        size: 'M',
        sku: 'VOR-SHT-004-CHR-M',
        price: 3890,
        stock_quantity: 18,
        is_active: true,
      },
      {
        id: 'v-s4-blk-l',
        product_id: 'prod-s4',
        color: 'Matte Charcoal',
        color_code: '#27272A',
        size: 'L',
        sku: 'VOR-SHT-004-CHR-L',
        price: 3890,
        stock_quantity: 14,
        is_active: true,
      },
      {
        id: 'v-s4-blk-xl',
        product_id: 'prod-s4',
        color: 'Matte Charcoal',
        color_code: '#27272A',
        size: 'XL',
        sku: 'VOR-SHT-004-CHR-XL',
        price: 3890,
        stock_quantity: 5,
        is_active: true,
      },
    ],
    created_at: '2026-03-04T10:00:00Z',
    updated_at: '2026-03-04T10:00:00Z',
  },

  {
    id: 'prod-s5',
    category_id: 'c-shirts',
    category_slug: 'shirts',
    category_name: 'Shirts',
    name: 'Heavyweight Utility Twill Overshirt',
    slug: 'heavyweight-utility-twill-overshirt',
    description:
      'Double-woven combed cotton twill engineered for maximum longevity and tactile presence. Finished with dual bellows chest pockets and reinforced elbow panels.',
    base_price: 5890,
    sale_price: 4990,
    sku: 'VOR-SHT-005',
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_on_sale: true,
    rating: 4.9,
    review_count: 31,
    images: [
      {
        id: 'img-s5-1',
        product_id: 'prod-s5',
        image_url: heroImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Heavyweight Utility Twill Overshirt',
      },
    ],
    variants: [
      {
        id: 'v-s5-olv-m',
        product_id: 'prod-s5',
        color: 'Military Olive',
        color_code: '#3F4E3E',
        size: 'M',
        sku: 'VOR-SHT-005-OLV-M',
        price: 5890,
        sale_price: 4990,
        stock_quantity: 11,
        is_active: true,
      },
      {
        id: 'v-s5-olv-l',
        product_id: 'prod-s5',
        color: 'Military Olive',
        color_code: '#3F4E3E',
        size: 'L',
        sku: 'VOR-SHT-005-OLV-L',
        price: 5890,
        sale_price: 4990,
        stock_quantity: 13,
        is_active: true,
      },
      {
        id: 'v-s5-blk-m',
        product_id: 'prod-s5',
        color: 'Obsidian Black',
        color_code: '#09090B',
        size: 'M',
        sku: 'VOR-SHT-005-BLK-M',
        price: 5890,
        sale_price: 4990,
        stock_quantity: 8,
        is_active: true,
      },
    ],
    created_at: '2026-03-05T10:00:00Z',
    updated_at: '2026-03-05T10:00:00Z',
  },

  // =========================
  // PANTS
  // =========================

  {
    id: 'prod-p1',
    category_id: 'c-pants',
    category_slug: 'pants',
    category_name: 'Pants',
    name: 'Vortex Tactical Utility Cargo Pants',
    slug: 'vortex-tactical-utility-cargo-pants',
    description:
      'Engineered from ultra-durable ripstop cotton-stretch blend with articulated knees, clean flat magnetic flap cargo pockets, and adjustable concealed ankle bungee drawstrings. Balances utilitarian functionality with modern tapered elegance.',
    base_price: 5290,
    sale_price: 4490,
    sku: 'VOR-PNT-001',
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: true,
    rating: 4.9,
    review_count: 42,
    images: [
      {
        id: 'img-p1-1',
        product_id: 'prod-p1',
        image_url: cargoPantsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Vortex Tactical Utility Cargo Pants in Charcoal',
      },
      {
        id: 'img-p1-2',
        product_id: 'prod-p1',
        image_url: categoryPantsImage,
        is_primary: false,
        sort_order: 2,
        alt_text: 'Vortex Cargo Pants pocket details',
      },
    ],
    variants: [
      {
        id: 'v-p1-chr-s',
        product_id: 'prod-p1',
        color: 'Charcoal Grey',
        color_code: '#334155',
        size: 'S',
        sku: 'VOR-PNT-001-CHR-S',
        price: 5290,
        sale_price: 4490,
        stock_quantity: 14,
        is_active: true,
      },
      {
        id: 'v-p1-chr-m',
        product_id: 'prod-p1',
        color: 'Charcoal Grey',
        color_code: '#334155',
        size: 'M',
        sku: 'VOR-PNT-001-CHR-M',
        price: 5290,
        sale_price: 4490,
        stock_quantity: 20,
        is_active: true,
      },
      {
        id: 'v-p1-chr-l',
        product_id: 'prod-p1',
        color: 'Charcoal Grey',
        color_code: '#334155',
        size: 'L',
        sku: 'VOR-PNT-001-CHR-L',
        price: 5290,
        sale_price: 4490,
        stock_quantity: 16,
        is_active: true,
      },
      {
        id: 'v-p1-chr-xl',
        product_id: 'prod-p1',
        color: 'Charcoal Grey',
        color_code: '#334155',
        size: 'XL',
        sku: 'VOR-PNT-001-CHR-XL',
        price: 5290,
        sale_price: 4490,
        stock_quantity: 8,
        is_active: true,
      },
      {
        id: 'v-p1-blk-m',
        product_id: 'prod-p1',
        color: 'Matte Black',
        color_code: '#18181B',
        size: 'M',
        sku: 'VOR-PNT-001-BLK-M',
        price: 5290,
        sale_price: 4490,
        stock_quantity: 12,
        is_active: true,
      },
    ],
    created_at: '2026-03-01T11:00:00Z',
    updated_at: '2026-03-01T11:00:00Z',
  },

  {
    id: 'prod-p2',
    category_id: 'c-pants',
    category_slug: 'pants',
    category_name: 'Pants',
    name: 'Tailored Pleated Wool-Blend Trousers',
    slug: 'tailored-pleated-wool-blend-trousers',
    description:
      'Single forward pleat tailored trousers cut with generous thigh volume tapering gently to a clean shoe break. Features an internal hidden drawstring alongside classic belt loops for versatile styling.',
    base_price: 5690,
    sku: 'VOR-PNT-002',
    is_active: true,
    is_featured: true,
    is_new_arrival: true,
    is_on_sale: false,
    rating: 4.8,
    review_count: 22,
    images: [
      {
        id: 'img-p2-1',
        product_id: 'prod-p2',
        image_url: categoryPantsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Tailored Pleated Wool-Blend Trousers',
      },
    ],
    variants: [
      {
        id: 'v-p2-ash-s',
        product_id: 'prod-p2',
        color: 'Ash Heather',
        color_code: '#94A3B8',
        size: 'S',
        sku: 'VOR-PNT-002-ASH-S',
        price: 5690,
        stock_quantity: 8,
        is_active: true,
      },
      {
        id: 'v-p2-ash-m',
        product_id: 'prod-p2',
        color: 'Ash Heather',
        color_code: '#94A3B8',
        size: 'M',
        sku: 'VOR-PNT-002-ASH-M',
        price: 5690,
        stock_quantity: 15,
        is_active: true,
      },
      {
        id: 'v-p2-ash-l',
        product_id: 'prod-p2',
        color: 'Ash Heather',
        color_code: '#94A3B8',
        size: 'L',
        sku: 'VOR-PNT-002-ASH-L',
        price: 5690,
        stock_quantity: 11,
        is_active: true,
      },
      {
        id: 'v-p2-nvy-m',
        product_id: 'prod-p2',
        color: 'Midnight Navy',
        color_code: '#0F172A',
        size: 'M',
        sku: 'VOR-PNT-002-NVY-M',
        price: 5690,
        stock_quantity: 10,
        is_active: true,
      },
    ],
    created_at: '2026-03-02T11:00:00Z',
    updated_at: '2026-03-02T11:00:00Z',
  },

  {
    id: 'prod-p3',
    category_id: 'c-pants',
    category_slug: 'pants',
    category_name: 'Pants',
    name: 'Everyday Slim Stretch Chino Pants',
    slug: 'everyday-slim-stretch-chino-pants',
    description:
      'Enzyme-softened twill with 3% spandex for exceptional flexibility. Designed with slant side pockets, clean welt back pockets, and double-stitched stress points.',
    base_price: 4190,
    sale_price: 3690,
    sku: 'VOR-PNT-003',
    is_active: true,
    is_featured: false,
    is_new_arrival: true,
    is_on_sale: true,
    rating: 4.7,
    review_count: 17,
    images: [
      {
        id: 'img-p3-1',
        product_id: 'prod-p3',
        image_url: categoryPantsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Everyday Slim Stretch Chino Pants',
      },
    ],
    variants: [
      {
        id: 'v-p3-khk-s',
        product_id: 'prod-p3',
        color: 'Desert Khaki',
        color_code: '#D1C2A5',
        size: 'S',
        sku: 'VOR-PNT-003-KHK-S',
        price: 4190,
        sale_price: 3690,
        stock_quantity: 16,
        is_active: true,
      },
      {
        id: 'v-p3-khk-m',
        product_id: 'prod-p3',
        color: 'Desert Khaki',
        color_code: '#D1C2A5',
        size: 'M',
        sku: 'VOR-PNT-003-KHK-M',
        price: 4190,
        sale_price: 3690,
        stock_quantity: 24,
        is_active: true,
      },
      {
        id: 'v-p3-khk-l',
        product_id: 'prod-p3',
        color: 'Desert Khaki',
        color_code: '#D1C2A5',
        size: 'L',
        sku: 'VOR-PNT-003-KHK-L',
        price: 4190,
        sale_price: 3690,
        stock_quantity: 18,
        is_active: true,
      },
    ],
    created_at: '2026-03-03T11:00:00Z',
    updated_at: '2026-03-03T11:00:00Z',
  },

  {
    id: 'prod-p4',
    category_id: 'c-pants',
    category_slug: 'pants',
    category_name: 'Pants',
    name: 'Relaxed Fit Linen Drawstring Pants',
    slug: 'relaxed-fit-linen-drawstring-pants',
    description:
      'Lightweight washed flax linen tailored with a comfortable elasticated drawstring waist and a relaxed straight-leg profile. Effortless drape that stays cool in warm Pakistani summers.',
    base_price: 4390,
    sku: 'VOR-PNT-004',
    is_active: true,
    is_featured: false,
    is_new_arrival: false,
    is_on_sale: false,
    rating: 4.8,
    review_count: 11,
    images: [
      {
        id: 'img-p4-1',
        product_id: 'prod-p4',
        image_url: categoryPantsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Relaxed Fit Linen Drawstring Pants',
      },
    ],
    variants: [
      {
        id: 'v-p4-nat-m',
        product_id: 'prod-p4',
        color: 'Natural Oatmeal',
        color_code: '#E2D9CC',
        size: 'M',
        sku: 'VOR-PNT-004-NAT-M',
        price: 4390,
        stock_quantity: 14,
        is_active: true,
      },
      {
        id: 'v-p4-nat-l',
        product_id: 'prod-p4',
        color: 'Natural Oatmeal',
        color_code: '#E2D9CC',
        size: 'L',
        sku: 'VOR-PNT-004-NAT-L',
        price: 4390,
        stock_quantity: 12,
        is_active: true,
      },
      {
        id: 'v-p4-blk-m',
        product_id: 'prod-p4',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'M',
        sku: 'VOR-PNT-004-BLK-M',
        price: 4390,
        stock_quantity: 9,
        is_active: true,
      },
    ],
    created_at: '2026-03-04T11:00:00Z',
    updated_at: '2026-03-04T11:00:00Z',
  },

  {
    id: 'prod-p5',
    category_id: 'c-pants',
    category_slug: 'pants',
    category_name: 'Pants',
    name: 'Architectural Wide-Leg Pleated Trousers',
    slug: 'architectural-wide-leg-trousers',
    description:
      'Substantial high-density structured twill cut in an assertive wide-leg silhouette with deep double reverse pleats and extended tab closure. An editorial centerpiece for distinctive dressing.',
    base_price: 5990,
    sale_price: 5190,
    sku: 'VOR-PNT-005',
    is_active: true,
    is_featured: true,
    is_new_arrival: false,
    is_on_sale: true,
    rating: 4.9,
    review_count: 26,
    images: [
      {
        id: 'img-p5-1',
        product_id: 'prod-p5',
        image_url: cargoPantsImage,
        is_primary: true,
        sort_order: 1,
        alt_text: 'Architectural Wide-Leg Pleated Trousers',
      },
    ],
    variants: [
      {
        id: 'v-p5-blk-s',
        product_id: 'prod-p5',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'S',
        sku: 'VOR-PNT-005-BLK-S',
        price: 5990,
        sale_price: 5190,
        stock_quantity: 7,
        is_active: true,
      },
      {
        id: 'v-p5-blk-m',
        product_id: 'prod-p5',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'M',
        sku: 'VOR-PNT-005-BLK-M',
        price: 5990,
        sale_price: 5190,
        stock_quantity: 13,
        is_active: true,
      },
      {
        id: 'v-p5-blk-l',
        product_id: 'prod-p5',
        color: 'Onyx Black',
        color_code: '#18181B',
        size: 'L',
        sku: 'VOR-PNT-005-BLK-L',
        price: 5990,
        sale_price: 5190,
        stock_quantity: 10,
        is_active: true,
      },
    ],
    created_at: '2026-03-05T11:00:00Z',
    updated_at: '2026-03-05T11:00:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    product_id: 'prod-s1',
    user_id: 'u-1',
    customer_name: 'Usman Farooq',
    rating: 5,
    review_text:
      'The weight of this overshirt is unbelievable. The Japanese cotton twill feels substantial, and the snap buttons give it an elevated minimalist touch. Fast COD delivery to Lahore in 2 days!',
    is_approved: true,
    created_at: '2026-03-12T14:30:00Z',
  },
  {
    id: 'rev-2',
    product_id: 'prod-p1',
    user_id: 'u-2',
    customer_name: 'Hamza Tariq',
    rating: 5,
    review_text:
      'Finally a cargo pant that looks sleek rather than baggy! The magnetic pockets are silent and low profile. Fits true to size, definitely ordering the black one next.',
    is_approved: true,
    created_at: '2026-03-15T09:15:00Z',
  },
  {
    id: 'rev-3',
    product_id: 'prod-s2',
    user_id: 'u-3',
    customer_name: 'Ali Raza',
    rating: 5,
    review_text:
      'Exceptional stitching on the collar and cuffs. High quality Egyptian cotton that holds its structure all day. The Vortex Wear is setting a new benchmark for menswear in Pakistan.',
    is_approved: true,
    created_at: '2026-03-18T18:40:00Z',
  },
];
